In [1]:
import numpy as np
import random
import pandas as pd

${\bf Steepest Descent Algorithm.}$
<hr>
    
Step 0: Given ${\bf x}^{0}$, set $k:=0$

Step 1: ${\bf d}^{k}:= -\nabla f({\bf x}^{k})$. If ${\bf d}^{k}=0$, then stop.

Step 2: Solve $\displaystyle \min_{\alpha >0} f({\bf x}^{k} + \alpha {\bf d}^{k})$ for the step size $\alpha^{k}$, perhaps chosen by an exact or inexact line search.

Step 3: Set ${\bf x}^{k+1} \leftarrow {\bf x}^{k} + \alpha^{k} {\bf d}^{k}$, $k \leftarrow k+1$.Go to Step 1.

Note from Step 2 and the fact that ${\bf d}^{k} = - \nabla f({\bf x}^{k})$
is a descent direction, it follows that $f({\bf x}^{k+1}) < f({\bf x}^{k}).$
<hr>

Consider the function $f({\bf x}) = 5x_{0}^{2} + x_{1}^{2} + 4x_{0}x_{1} - 14x_{0} - 6x_{1} +20$.

Define
$$
{\bf x}=
\left[\begin{array}{cc}
x_{0}\\
x_{1}
\end{array}\right],
Q=
\left[\begin{array}{cc}
10&4\\
4&2
\end{array}\right]
\hbox{ and }
{\bf q}=
\left[\begin{array}{cc}
-14\\
-6
\end{array}\right].
$$

Then $f({\bf x})=\displaystyle \frac{1}{2}{\bf x}^tQ{\bf x}+{\bf q}^t {\bf x}+20$. Hence the optimal solution is
$$
{\bf x}^{*}=\left[\begin{array}{cc}
10&4\\
4&2
\end{array}\right]^{-1}\left[\begin{array}{cc}
-14\\
-6
\end{array}\right]=\left[\begin{array}{cc}
1\\
1
\end{array}\right]\hbox{ and } f(1,1)=10.
$$
This function has its optimal solution at
${\bf x}^{*} = (x_{0}^{*},x_{1}^{*}) = (1,1)$ and $f(1,1)=10$.
The descent direction can be
$$
{\bf d}^{k} =
%\left[
%\begin{array}{c}
%    d_{1}^{k} \\
%    d_{2}^{k}
%\end{array}
%\right]=
-\nabla f({\bf x}^k) =
\left[
\begin{array}{c}
    -10x_{0}^{k}-4x_{1}^{k}+14  \\
    -2x_{1}^{k}-4x_{0}^{k}+6
\end{array}
\right]
$$ 
<hr>

In [2]:
#define a subroutine
def feval(x0,x1):
    y=5*x0**2+x1**2+4*x0*x1-14*x0-6*x1+20
    return y

In [3]:
def gfeval(x0,x1):
    y0=-10*x0-4*x1+14
    y1=-2*x1-4*x0+6
    return y0,y1

In [4]:
feval(0,10)

60

In [5]:
gfeval(0,10)

(-26, -14)

In [6]:
d0,d1=gfeval(0,10)
print(d0)
print(d1)

-26
-14

In [7]:
d0*d0+d1*d1

872

In [8]:
10*d0*d0+8*d0*d1+2*d1*d1

10064

In [9]:
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
alpha

0.08664546899841018

In [10]:
#define an array and modify the components

In [11]:
Q=np.array([[[10],[4]],[[4],[2]]])
print(Q[0,0])
print(Q[0,0])
print(Q[0,0])
print(Q[1,1])

[10]
[10]
[10]
[2]

In [12]:
x=np.array([[[1]],[[1]]])
print(x[0,0])
print(x[1,0])

[1]
[1]

In [13]:
q=np.array([[[-14]],[[-6]]])
print(q[0,0])
print(q[1,0])

[-14]
[-6]

In [14]:
y=np.matmul(np.transpose(x),Q)
y

array([[[14]],

       [[ 6]]])

In [15]:
#simplly show the value of variable

In [16]:
x0,x1,k=0,10,0
d0,d1=gfeval(x0,x1)
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
print(x0,x1,d0,d1,np.sqrt(d0*d0+d1*d1),alpha,feval(x0,x1))
x0=x0+alpha*d0
x1=x1+alpha*d1
print(x0,x1)

0 10 -26 -14 29.5296461204668 0.08664546899841018 60
-2.2527821939586645 8.786963434022258

In [17]:
x0,x1,k=0,10,1

d0,d1=gfeval(x0,x1)
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
print('k=%d' % k,x0,x1,d0,d1,np.sqrt(d0*d0+d1*d1),alpha,feval(x0,x1))
x0=x0+alpha*d0
x1=x1+alpha*d1
k=k+1

d0,d1=gfeval(x0,x1)
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
print('k=%d' % k,x0,x1,d0,d1,np.sqrt(d0*d0+d1*d1),alpha,feval(x0,x1))
x0=x0+alpha*d0
x1=x1+alpha*d1
k=k+1

print('k=%d' % k,x0,x1)

k=1 0 10 -26 -14 29.5296461204668 0.08664546899841018 60
k=2 -2.2527821939586645 8.786963434022258 1.3799682034976115 -2.5627980922098583 2.910712336198635 2.1800000000000157 22.222575516693176
k=3 0.7555484896661504 3.200063593004727

In [18]:
d0,d1=gfeval(x0,x1)
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
norm_d=np.sqrt(d0*d0+d1*d1)
print('k=%d' % k,x0,x1,d0,d1,norm_d,alpha,feval(x0,x1))
x0=x0+alpha*d0
x1=x1+alpha*d1
k=k+1

d0,d1=gfeval(x0,x1)
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
norm_d=np.sqrt(d0*d0+d1*d1)
print('k=%d' % k,x0,x1,d0,d1,norm_d,alpha,feval(x0,x1))
x0=x0+alpha*d0
x1=x1+alpha*d1
k=k+1

d0,d1=gfeval(x0,x1)
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
norm_d=np.sqrt(d0*d0+d1*d1)
print('k=%d' % k,x0,x1,d0,d1,norm_d,alpha,feval(x0,x1))
x0=x0+alpha*d0
x1=x1+alpha*d1
k=k+1

d0,d1=gfeval(x0,x1)
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
norm_d=np.sqrt(d0*d0+d1*d1)
print('k=%d' % k,x0,x1,d0,d1,norm_d,alpha,feval(x0,x1))
x0=x0+alpha*d0
x1=x1+alpha*d1
k=k+1

d0,d1=gfeval(x0,x1)
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
norm_d=np.sqrt(d0*d0+d1*d1)
print('k=%d' % k,x0,x1,d0,d1,norm_d,alpha,feval(x0,x1))
x0=x0+alpha*d0
x1=x1+alpha*d1
k=k+1

d0,d1=gfeval(x0,x1)
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
norm_d=np.sqrt(d0*d0+d1*d1)
print('k=%d' % k,x0,x1,d0,d1,norm_d,alpha,feval(x0,x1))
x0=x0+alpha*d0
x1=x1+alpha*d1
k=k+1

d0,d1=gfeval(x0,x1)
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
norm_d=np.sqrt(d0*d0+d1*d1)
print('k=%d' % k,x0,x1,d0,d1,norm_d,alpha,feval(x0,x1))
x0=x0+alpha*d0
x1=x1+alpha*d1
k=k+1

d0,d1=gfeval(x0,x1)
alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
norm_d=np.sqrt(d0*d0+d1*d1)
print('k=%d' % k,x0,x1,d0,d1,norm_d,alpha,feval(x0,x1))
x0=x0+alpha*d0
x1=x1+alpha*d1
k=k+1

k=3 0.7555484896661504 3.200063593004727 -6.355739268680413 -3.422321144674056 7.218566593772573 0.08664546899841015 12.987827045225288
k=4 0.20485247989972366 2.9035349723612676 0.3373353115576929 -0.6264798643214302 0.7115280267311495 2.1800000000000033 10.730378833821668
k=5 0.9402434590954953 1.5378088681405477 -1.5536700635171456 -0.8365915726630764 1.7645895062932486 0.08664546899841016 10.178542209043592
k=6 0.8056249877732625 1.4653219989670379 0.08246212639922312 -0.15314394902712536 0.17393410077930155 2.1799999999999033 10.04364491265905
k=7 0.9853924233235609 1.1314681900879193 -0.3797969935872878 -0.20450607347008187 0.43135656993268673 0.08664546899841032 10.010669064817897
k=8 0.9524847346900042 1.1137486654390807 0.020157991343634052 -0.03743626963817803 0.04251845363406807 2.180000000000061 10.002608069008586
k=9 0.9964291558191276 1.0321375976278504 -0.09284194870267726 -0.04999181853221124 0.10544576501248447 0.08664546899841023 10.000637546408203
k=10 0.9883848216310578 1.0278060330650436 0.004927651429246893 -0.009151352654318323 0.010393700207907575 2.1800000000013156 10.000155849182395

In [19]:
x0,x1,k=0,10,1
d0,d1=gfeval(x0,x1)
norm_d=np.sqrt(d0*d0+d1*d1)

while norm_d>0.00001:
    d0,d1=gfeval(x0,x1)
    alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
    norm_d=np.sqrt(d0*d0+d1*d1)
    print('k=%d' % k,x0,x1,d0,d1,norm_d,alpha,feval(x0,x1))
    x0=x0+alpha*d0
    x1=x1+alpha*d1
    k=k+1

k=1 0 10 -26 -14 29.5296461204668 0.08664546899841018 60
k=2 -2.2527821939586645 8.786963434022258 1.3799682034976115 -2.5627980922098583 2.910712336198635 2.1800000000000157 22.222575516693176
k=3 0.7555484896661504 3.200063593004727 -6.355739268680413 -3.422321144674056 7.218566593772573 0.08664546899841015 12.987827045225288
k=4 0.20485247989972366 2.9035349723612676 0.3373353115576929 -0.6264798643214302 0.7115280267311495 2.1800000000000033 10.730378833821668
k=5 0.9402434590954953 1.5378088681405477 -1.5536700635171456 -0.8365915726630764 1.7645895062932486 0.08664546899841016 10.178542209043592
k=6 0.8056249877732625 1.4653219989670379 0.08246212639922312 -0.15314394902712536 0.17393410077930155 2.1799999999999033 10.04364491265905
k=7 0.9853924233235609 1.1314681900879193 -0.3797969935872878 -0.20450607347008187 0.43135656993268673 0.08664546899841032 10.010669064817897
k=8 0.9524847346900042 1.1137486654390807 0.020157991343634052 -0.03743626963817803 0.04251845363406807 2.180000000000061 10.002608069008586
k=9 0.9964291558191276 1.0321375976278504 -0.09284194870267726 -0.04999181853221124 0.10544576501248447 0.08664546899841023 10.000637546408203
k=10 0.9883848216310578 1.0278060330650436 0.004927651429246893 -0.009151352654318323 0.010393700207907575 2.1800000000013156 10.000155849182395
k=11 0.9991271017468225 1.0078560842786175 -0.02269535458269445 -0.012220575544525047 0.02577637651559415 0.08664546899840858 10.000038097568018
k=12 0.9971606521049198 1.0067972267791316 0.0012045718342754697 -0.0022370619779419343 0.002540755713775578 2.180000000003585 10.00000931300804
k=13 0.9997866187036446 1.0019204316672101 -0.0055479137052873995 -0.002987338148998653 0.006301074170153726 0.0866454689984048 10.000002276578883
k=14 0.9993059171186873 1.0016615923522334 0.0002944594041931481 -0.0005468531792161002 0.0006210915716193064 2.180000000002094 10.000000556513145
k=15 0.999947838619829 1.0004694524215412 -0.0013561958844547917 -0.0007302593223990073 0.0015403070976148787 0.08664546899841284 10.00000013604048
k=16 0.9998303303913667 1.0004061787600615 7.198104608718836e-05 -0.0001336790855894776 0.0001518267727373694 2.1799999999657267 10.0000000332553
k=17 0.9999872490718343 1.000114758353481 -0.0003315241322674467 -0.00017851299429949563 0.00037653039639510546 0.08664546899847568 10.000000008129309
k=18 0.9999585240079097 1.0000992910113677 1.759587543048724e-05 -3.267805437445759e-05 3.711428390613554e-05 2.180000000490711 10.000000001987221
k=19 0.9999968830163568 1.0000280528528154 -8.104157482868857e-05 -4.36377710579805e-05 9.204342406507186e-05 0.08664546899781853 10.00000000048578
k=20 0.9999898611310974 1.000024271837676 4.301338321965886e-06 -7.988199741681967e-06 9.072642750214523e-06 2.180000000501849 10.000000000118748

In [20]:
iterationNo=[]
iterationX1=[]
iterationX2=[]
iterationX3=[]
iterationX4=[]
iterationX5=[]
iterationX6=[]
iterationX7=[]

x0,x1,k=0,10,1
d0,d1=gfeval(x0,x1)
norm_d=np.sqrt(d0*d0+d1*d1)

while norm_d>0.00001:
    d0,d1=gfeval(x0,x1)
    alpha=(d0*d0+d1*d1)/(10*d0*d0+8*d0*d1+2*d1*d1)
    norm_d=np.sqrt(d0*d0+d1*d1)
    #print('k=%d' % k,x0,x1,d0,d1,norm_d,alpha,feval(x0,x1))
    
    iterationNo.append(k)
    iterationX1.append(x0)
    iterationX2.append(x1)
    iterationX3.append(d0)
    iterationX4.append(d1)
    iterationX5.append(norm_d)
    iterationX6.append(alpha)
    iterationX7.append(feval(x0,x1))
    
    x0=x0+alpha*d0
    x1=x1+alpha*d1
    k=k+1

Table={"k":iterationNo,"$x_{0}$":iterationX1,"$x_{1}$":iterationX2,"$d_{0}$":iterationX3,"$d_{1}$":iterationX4,"norm_d":iterationX5,"alpha":iterationX6,"fvalue":iterationX7}
pd.DataFrame(Table)

,k,$x_{0}$,$x_{1}$,$d_{0}$,$d_{1}$,norm_d,alpha,fvalue
0,1,0.000000,10.000000,-26.000000,-14.000000,29.529646,0.086645,60.000000
1,2,-2.252782,8.786963,1.379968,-2.562798,2.910712,2.180000,22.222576
2,3,0.755548,3.200064,-6.355739,-3.422321,7.218567,0.086645,12.987827
3,4,0.204852,2.903535,0.337335,-0.626480,0.711528,2.180000,10.730379
4,5,0.940243,1.537809,-1.553670,-0.836592,1.764590,0.086645,10.178542
5,6,0.805625,1.465322,0.082462,-0.153144,0.173934,2.180000,10.043645
6,7,0.985392,1.131468,-0.379797,-0.204506,0.431357,0.086645,10.010669
7,8,0.952485,1.113749,0.020158,-0.037436,0.042518,2.180000,10.002608
8,9,0.996429,1.032138,-0.092842,-0.049992,0.105446,0.086645,10.000638
9,10,0.988385,1.027806,0.004928,-0.009151,0.010394,2.180000,10.000156
10,11,0.999127,1.007856,-0.022695,-0.012221,0.025776,0.086645,10.000038
11,12,0.997161,1.006797,0.001205,-0.002237,0.002541,2.180000,10.000009
12,13,0.999787,1.001920,-0.005548,-0.002987,0.006301,0.086645,10.000002
13,14,0.999306,1.001662,0.000294,-0.000547,0.000621,2.180000,10.000001
14,15,0.999948,1.000469,-0.001356,-0.000730,0.001540,0.086645,10.000000
15,16,0.999830,1.000406,0.000072,-0.000134,0.000152,2.180000,10.000000
16,17,0.999987,1.000115,-0.000332,-0.000179,0.000377,0.086645,10.000000
17,18,0.999959,1.000099,0.000018,-0.000033,0.000037,2.180000,10.000000
18,19,0.999997,1.000028,-0.000081,-0.000044,0.000092,0.086645,10.000000
19,20,0.999990,1.000024,0.000004,-0.000008,0.000009,2.180000,10.000000

In [21]:
iterationNo=[]
iterationX1=[]
iterationX2=[]
iterationX3=[]
iterationX4=[]
iterationX5=[]
iterationX6=[]
iterationX7=[]
iterationX8=[]
iterationX9=[]

def feval(x0,x1,x2):
    y=0.5*(10*x0*x0+40*x1*x1+3*x2*x2-36*x0*x1+4*x0*x2-2*x1*x2)+12*x0-47*x1-8*x2
    return y

def gfeval(x0,x1,x2):
    y0=-10*x0+18*x1-2*x2-12
    y1=-40*x1+18*x0+x2+47
    y2=-3*x2-2*x0+x1+8
    return y0,y1,y2

x0,x1,x2,k=0,0,0,1
d0,d1,d2=gfeval(x0,x1,x2)
norm_d=np.sqrt(d0*d0+d1*d1+d2*d2)

while norm_d>0.1:
    d0,d1,d2=gfeval(x0,x1,x2)
    alpha=(d0*d0+d1*d1+d2*d2)/(10*d0*d0+40*d1*d1+3*d2*d2-36*d0*d1+4*d0*d2-2*d1*d2)
    norm_d=np.sqrt(d0*d0+d1*d1+d2*d2)
    
    iterationNo.append(k)
    iterationX1.append(x0)
    iterationX2.append(x1)
    iterationX3.append(x2)
    iterationX4.append(d0)
    iterationX5.append(d1)
    iterationX6.append(d2)
    iterationX7.append(norm_d)
    iterationX8.append(alpha)
    iterationX9.append(feval(x0,x1,x2))
    
    x0=x0+alpha*d0
    x1=x1+alpha*d1
    x2=x2+alpha*d2
    k=k+1

Table={"k":iterationNo,"$x_{0}$":iterationX1,"$x_{1}$":iterationX2,"$x_{2}$":iterationX3,"$d_{0}$":iterationX4,"$d_{1}$":iterationX5,"$d_{2}$":iterationX6,"norm_d":iterationX7,"alpha":iterationX8,"fvalue":iterationX9}
pd.DataFrame(Table)

,k,$x_{0}$,$x_{1}$,$x_{2}$,$d_{0}$,$d_{1}$,$d_{2}$,norm_d,alpha,fvalue
0,1,0.000000,0.000000,0.000000,-12.000000,47.000000,8.000000,49.162994,0.022142,0.000000
1,2,-0.265702,1.040665,0.177134,9.034720,0.767900,9.040665,12.804275,0.142798,-26.758378
2,3,1.024435,1.150319,1.468120,-4.474837,20.895167,2.697090,21.538488,0.022206,-38.464173
3,4,0.925069,1.614308,1.528010,4.750832,0.606938,3.180140,5.749093,0.147853,-43.614817
4,5,1.627492,1.704045,1.998203,-1.598514,10.131255,0.454453,10.266650,0.022413,-46.058237
5,6,1.591664,1.931119,2.008388,2.826722,0.413587,0.722625,2.946795,0.161412,-47.239458
6,7,2.047931,1.997877,2.125029,-0.767582,6.072709,-0.473070,6.139281,0.022751,-47.940276
7,8,2.030468,2.136036,2.114266,1.915435,0.221254,-0.267697,1.946666,0.174851,-48.369023
8,9,2.365384,2.174722,2.067459,-0.643756,4.655478,-0.758422,4.760578,0.022899,-48.700324
9,10,2.350643,2.281326,2.050092,1.457261,0.108612,-0.570235,1.568622,0.178490,-48.959800
10,11,2.610750,2.300712,1.948310,-0.591296,3.913311,-0.765719,4.031124,0.022922,-49.179395
11,12,2.597196,2.390414,1.930758,1.193969,0.063738,-0.596254,1.336093,0.178990,-49.365636
12,13,2.810905,2.401822,1.824035,-0.524320,3.347435,-0.692092,3.458211,0.022925,-49.525398
13,14,2.798885,2.478562,1.808169,1.008929,0.045617,-0.543714,1.147015,0.179049,-49.662481
14,15,2.979533,2.486730,1.710817,-0.455830,2.873223,-0.604788,2.971357,0.022925,-49.780263
15,16,2.969083,2.552599,1.696952,0.862050,0.036479,-0.476423,0.985617,0.179056,-49.881466
16,17,3.123439,2.559131,1.611645,-0.393319,2.468298,-0.522683,2.553506,0.022925,-49.968438
17,18,3.114422,2.615718,1.599663,0.739374,0.030549,-0.412114,0.847021,0.179057,-50.043179
18,19,3.246812,2.621188,1.525871,-0.338483,2.120979,-0.450049,2.194462,0.022925,-50.107411
19,20,3.239052,2.669812,1.515553,0.634985,0.026019,-0.354952,0.727924,0.179057,-50.162611
20,21,3.352751,2.674471,1.451996,-0.291028,1.822681,-0.387020,1.885908,0.022925,-50.210050
21,22,3.346079,2.716256,1.443124,0.545577,0.022292,-0.305273,0.625574,0.179057,-50.250819
22,23,3.443768,2.720248,1.388462,-0.250148,1.566380,-0.332676,1.620738,0.022925,-50.285855
23,24,3.438034,2.756158,1.380836,0.468829,0.019137,-0.262417,0.537614,0.179057,-50.315965
24,25,3.521981,2.759584,1.333848,-0.214987,1.346131,-0.285922,1.392853,0.022925,-50.341841
25,26,3.517052,2.790445,1.327293,0.402898,0.016441,-0.225539,0.462023,0.179057,-50.364079
26,27,3.589194,2.793389,1.286909,-0.184762,1.156855,-0.245726,1.197010,0.022925,-50.383191
27,28,3.584958,2.819910,1.281275,0.346245,0.014127,-0.193833,0.397060,0.179057,-50.399615
28,29,3.646956,2.822440,1.246568,-0.158785,0.994194,-0.211177,1.028703,0.022925,-50.413729
29,30,3.643316,2.845232,1.241727,0.297560,0.012140,-0.166581,0.341231,0.179057,-50.425860
30,31,3.696596,2.847406,1.211899,-0.136459,0.854405,-0.181485,0.884062,0.022925,-50.436284
31,32,3.693468,2.866993,1.207739,0.255721,0.010433,-0.143159,0.293252,0.179057,-50.445243
32,33,3.739256,2.868861,1.182105,-0.117272,0.734271,-0.155967,0.759758,0.022925,-50.452942
33,34,3.736568,2.885695,1.178530,0.219765,0.008966,-0.123030,0.252019,0.179057,-50.459559
34,35,3.775919,2.887300,1.156500,-0.100783,0.631028,-0.134037,0.652931,0.022925,-50.465245
35,36,3.773608,2.901767,1.153427,0.188865,0.007706,-0.105731,0.216584,0.179057,-50.470132
36,37,3.807426,2.903146,1.134495,-0.086612,0.542302,-0.115191,0.561125,0.022925,-50.474331
37,38,3.805440,2.915579,1.131855,0.162309,0.006622,-0.090865,0.186131,0.179057,-50.477941
38,39,3.834503,2.916765,1.115585,-0.074434,0.466051,-0.098994,0.482228,0.022925,-50.481042
39,40,3.832796,2.927449,1.113315,0.139488,0.005691,-0.078089,0.159960,0.179057,-50.483708
40,41,3.857773,2.928468,1.099333,-0.063968,0.400522,-0.085075,0.414424,0.022925,-50.485999
41,42,3.856306,2.937650,1.097382,0.119875,0.004891,-0.067109,0.137468,0.179057,-50.487967
42,43,3.877771,2.938526,1.085366,-0.054974,0.344206,-0.073113,0.356154,0.022925,-50.489659
43,44,3.876510,2.946417,1.083690,0.103020,0.004203,-0.057673,0.118140,0.179057,-50.491113
44,45,3.894957,2.947169,1.073363,-0.047244,0.295809,-0.062833,0.306076,0.022925,-50.492363
45,46,3.893874,2.953951,1.071923,0.088535,0.003612,-0.049564,0.101528,0.179057,-50.493437
46,47,3.909726,2.954598,1.063048,-0.040601,0.254216,-0.053998,0.263040,0.022925,-50.494359
47,48,3.908796,2.960426,1.061810,0.076086,0.003104,-0.042595,0.087253,0.179057,-50.495152

In [22]:
iterationNo=[]
iterationX1=[]
iterationX2=[]
iterationX3=[]
iterationX4=[]
iterationX5=[]
iterationX6=[]
iterationX7=[]
iterationX8=[]
iterationX9=[]

def feval(x0,x1,x2):
    y=0.5*(10*x0*x0+40*x1*x1+3*x2*x2-36*x0*x1+4*x0*x2-2*x1*x2)+12*x0-47*x1-8*x2
    return y

def gfeval(x0,x1,x2):
    y0=-10*x0+18*x1-2*x2-12
    y1=-40*x1+18*x0+x2+47
    y2=-3*x2-2*x0+x1+8
    return y0,y1,y2

x0,x1,x2,k=15.09,7.66,-6.56,1
d0,d1,d2=gfeval(x0,x1,x2)
norm_d=np.sqrt(d0*d0+d1*d1+d2*d2)

while norm_d>0.1:
    d0,d1,d2=gfeval(x0,x1,x2)
    alpha=(d0*d0+d1*d1+d2*d2)/(10*d0*d0+40*d1*d1+3*d2*d2-36*d0*d1+4*d0*d2-2*d1*d2)
    norm_d=np.sqrt(d0*d0+d1*d1+d2*d2)
    
    iterationNo.append(k)
    iterationX1.append(x0)
    iterationX2.append(x1)
    iterationX3.append(x2)
    iterationX4.append(d0)
    iterationX5.append(d1)
    iterationX6.append(d2)
    iterationX7.append(norm_d)
    iterationX8.append(alpha)
    iterationX9.append(feval(x0,x1,x2))
    
    x0=x0+alpha*d0
    x1=x1+alpha*d1
    x2=x2+alpha*d2
    k=k+1

Table={"k":iterationNo,"$x_{0}$":iterationX1,"$x_{1}$":iterationX2,"$x_{2}$":iterationX3,"$d_{0}$":iterationX4,"$d_{1}$":iterationX5,"$d_{2}$":iterationX6,"norm_d":iterationX7,"alpha":iterationX8,"fvalue":iterationX9}
pd.DataFrame(Table)

,k,$x_{0}$,$x_{1}$,$x_{2}$,$d_{0}$,$d_{1}$,$d_{2}$,norm_d,alpha,fvalue
0,1,15.090000,7.660000,-6.560000,-11.900000,5.660000,5.160000,14.151721,0.040887,21.802500
1,2,14.603440,7.891423,-6.349021,-3.290753,-12.144001,5.731606,13.825958,0.040405,17.708218
2,3,14.470477,7.400743,-6.117435,-11.256526,5.321432,4.812094,13.348531,0.040888,13.846356
3,4,14.010218,7.618327,-5.920677,-3.130938,-11.469835,5.359923,13.041804,0.040406,10.203557
4,5,13.883710,7.154880,-5.704105,-10.641049,5.007476,4.499777,12.591852,0.040889,6.767279
...,...,...,...,...,...,...,...,...,...,...
167,168,4.084474,3.038988,0.942052,-0.027054,-0.096946,0.043886,0.109802,0.040407,-50.495696
168,169,4.083380,3.035071,0.943825,-0.090180,0.041841,0.036835,0.106018,0.040889,-50.495939
169,170,4.079693,3.036782,0.945331,-0.025523,-0.091460,0.041402,0.103588,0.040407,-50.496169
170,171,4.078662,3.033086,0.947004,-0.085076,0.039473,0.034750,0.100018,0.040889,-50.496386
171,172,4.075183,3.034700,0.948425,-0.024079,-0.086284,0.039059,0.097726,0.040407,-50.496591

In [23]:
iterationNo=[]
iterationX1=[]
iterationX2=[]
iterationX3=[]
iterationX4=[]
iterationX5=[]
iterationX6=[]
iterationX7=[]
iterationX8=[]
iterationX9=[]

def feval(x0,x1,x2):
    y=0.5*(10*x0*x0+40*x1*x1+3*x2*x2-36*x0*x1+4*x0*x2-2*x1*x2)+12*x0-47*x1-8*x2
    return y

def gfeval(x0,x1,x2):
    y0=-10*x0+18*x1-2*x2-12
    y1=-40*x1+18*x0+x2+47
    y2=-3*x2-2*x0+x1+8
    return y0,y1,y2

x0,x1,x2,k=11.77,6.42,-4.28,1
d0,d1,d2=gfeval(x0,x1,x2)
norm_d=np.sqrt(d0*d0+d1*d1+d2*d2)

while norm_d>0.1:
    d0,d1,d2=gfeval(x0,x1,x2)
    alpha=(d0*d0+d1*d1+d2*d2)/(10*d0*d0+40*d1*d1+3*d2*d2-36*d0*d1+4*d0*d2-2*d1*d2)
    norm_d=np.sqrt(d0*d0+d1*d1+d2*d2)
    
    iterationNo.append(k)
    iterationX1.append(x0)
    iterationX2.append(x1)
    iterationX3.append(x2)
    iterationX4.append(d0)
    iterationX5.append(d1)
    iterationX6.append(d2)
    iterationX7.append(norm_d)
    iterationX8.append(alpha)
    iterationX9.append(feval(x0,x1,x2))
    
    x0=x0+alpha*d0
    x1=x1+alpha*d1
    x2=x2+alpha*d2
    k=k+1

Table={"k":iterationNo,"$x_{0}$":iterationX1,"$x_{1}$":iterationX2,"$x_{2}$":iterationX3,"$d_{0}$":iterationX4,"$d_{1}$":iterationX5,"$d_{2}$":iterationX6,"norm_d":iterationX7,"alpha":iterationX8,"fvalue":iterationX9}
pd.DataFrame(Table)

,k,$x_{0}$,$x_{1}$,$x_{2}$,$d_{0}$,$d_{1}$,$d_{2}$,norm_d,alpha,fvalue
0,1,11.770000,6.420000,-4.280000,-5.580000,-2.220000,3.720000,7.064220,1.329051,-15.204700
1,2,4.353896,3.469507,0.664069,5.584027,-12.746082,0.769507,13.936862,0.020639,-48.366644
2,3,4.469144,3.206442,0.679951,-0.335382,-0.133147,0.228301,0.427002,1.328563,-50.371051
3,4,4.023568,3.029548,0.983263,0.329659,-0.774437,0.032622,0.842313,0.020646,-50.492170
4,5,4.030375,3.013559,0.983937,-0.027554,-0.011687,0.001000,0.029947,0.650336,-50.499494

In [24]:
iterationNo=[]
iterationX1=[]
iterationX2=[]
iterationX3=[]
iterationX4=[]
iterationX5=[]
iterationX6=[]
iterationX7=[]
iterationX8=[]
iterationX9=[]

def feval(x0,x1,x2):
    y=0.5*(10*x0*x0+40*x1*x1+3*x2*x2-36*x0*x1+4*x0*x2-2*x1*x2)+12*x0-47*x1-8*x2
    return y

def gfeval(x0,x1,x2):
    y0=-10*x0+18*x1-2*x2-12
    y1=-40*x1+18*x0+x2+47
    y2=-3*x2-2*x0+x1+8
    return y0,y1,y2

x0,x1,x2,k=4.46,2.25,1.85,1
d0,d1,d2=gfeval(x0,x1,x2)
norm_d=np.sqrt(d0*d0+d1*d1+d2*d2)

while norm_d>0.1:
    d0,d1,d2=gfeval(x0,x1,x2)
    alpha=(d0*d0+d1*d1+d2*d2)/(10*d0*d0+40*d1*d1+3*d2*d2-36*d0*d1+4*d0*d2-2*d1*d2)
    norm_d=np.sqrt(d0*d0+d1*d1+d2*d2)
    
    iterationNo.append(k)
    iterationX1.append(x0)
    iterationX2.append(x1)
    iterationX3.append(x2)
    iterationX4.append(d0)
    iterationX5.append(d1)
    iterationX6.append(d2)
    iterationX7.append(norm_d)
    iterationX8.append(alpha)
    iterationX9.append(feval(x0,x1,x2))
    
    x0=x0+alpha*d0
    x1=x1+alpha*d1
    x2=x2+alpha*d2
    k=k+1

Table={"k":iterationNo,"$x_{0}$":iterationX1,"$x_{1}$":iterationX2,"$x_{2}$":iterationX3,"$d_{0}$":iterationX4,"$d_{1}$":iterationX5,"$d_{2}$":iterationX6,"norm_d":iterationX7,"alpha":iterationX8,"fvalue":iterationX9}
pd.DataFrame(Table)

,k,$x_{0}$,$x_{1}$,$x_{2}$,$d_{0}$,$d_{1}$,$d_{2}$,norm_d,alpha,fvalue
0,1,4.460000,2.250000,1.850000,-19.800000,39.130000,-4.220000,44.056842,0.020698,-29.478750
1,2,4.050175,3.059921,1.762654,-0.948477,-0.731042,-2.328390,2.618288,0.252921,-49.566425
2,3,3.810285,2.875025,1.173755,-0.699905,1.757874,-0.266809,1.910805,0.020900,-50.433367
3,4,3.795657,2.911766,1.168178,0.118854,0.019382,-0.184083,0.219974,0.511303,-50.471522
4,5,3.856427,2.921676,1.074056,-0.122222,0.622718,-0.013347,0.634739,0.021868,-50.483893
5,6,3.853754,2.935293,1.073764,0.150203,0.029620,0.006492,0.153233,0.225379,-50.488298
6,7,3.887607,2.941969,1.075227,-0.071088,0.373404,-0.058927,0.384651,0.022234,-50.490944
7,8,3.886027,2.950271,1.073917,0.096779,0.011554,-0.043533,0.106746,0.234535,-50.492589
8,9,3.908725,2.952981,1.063707,-0.061003,0.301512,-0.055589,0.312603,0.022249,-50.493925
9,10,3.907367,2.959689,1.062470,0.075795,0.007508,-0.042456,0.087199,0.234747,-50.495012

In [25]:
#design a for-loop

In [26]:
#design a while-loop

In [27]:
#design a if and else

In [28]:
#design a pandas dataframe

In [29]:
#目標式
def functionValue(x):
    y=5*x[0,0]**2+x[1,0]**2+4*x[0,0]*x[1,0]-14*x[0,0]-6*x[1,0]+20
    return y

#一階微分(未加負號)
def functionGradient(x):
    #d=
    d=np.array(d)
    return d

In [30]:
#x0=1, x1=1
xk=np.array([[[1],[1]]])
print(xk)

[[[1]
  [1]]]

In [31]:
xk[0]

array([[1],
       [1]])

In [32]:
#測試目標值
functionValue(xk[0])

10

<hr>
Step 0: Given ${\bf x}^{0}$, set $k:=0$

In [33]:
#隨機給定x0,x1
xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0

In [34]:
print(xk)

[array([[5],
       [0]])]

<hr>
Step 1: ${\bf d}^{k}:= -\nabla f({\bf x}^{k})$. If ${\bf d}^{k}=0$, then stop.

In [35]:
dk=[-functionGradient(xk[0])]
print(dk)

UnboundLocalError: local variable 'd' referenced before assignment

<hr>
Step 2: Solve $\displaystyle \min_{\alpha >0} f({\bf x}^{k} + \alpha {\bf d}^{k})$ for the step size $\alpha^{k}$, perhaps chosen by an exact or inexact line search.

$$
f({\bf x}) = 5x_{0}^{2} + x_{1}^{2} + 4x_{0}x_{1} - 14x_{0} - 6x_{1} +20
$$.
$$
\begin{array}{rcl}
f({\bf x}+\alpha {\bf d}) &= &5(x_{0}+\alpha d_{0})^{2} + (x_{1}+\alpha d_{1})^{2} + 4(x_{0}+\alpha d_{0})(x_{1}+\alpha d_{1}) - 14(x_{0}+\alpha d_{0}) - 6(x_{1}+\alpha d_{1}) +20\\
& = & (5d_{0}^{2}+d_{1}^{2}+4d_{0}d_{1}) \alpha^2 +(10x_{0}d_{0}+2x_{1}d_{1}+4x_{1}d_{0}+4x_{0}d_{1}-14d_{0}-6d_{1})\alpha +5x_{0}^{2} + x_{1}^{2} + 4x_{0}x_{1} - 14x_{0} - 6x_{1} +20\\
\end{array}
$$
Hence 
$$
\frac{d}{d \alpha} f({\bf x}+\alpha {\bf d})=2(5d_{0}^{2}+d_{1}^{2}+4d_{0}d_{1}) \alpha +10x_{0}d_{0}+2x_{1}d_{1}+4x_{1}d_{0}+4x_{0}d_{1}-14d_{0}-6d_{1}
$$
and the minimum solution of $\displaystyle \min_{\alpha >0} f({\bf x}^{k} + \alpha {\bf d}^{k})$ is given by
$$
\alpha^{*}=-\frac{10x_{0}d_{0}+2x_{1}d_{1}+4x_{1}d_{0}+4x_{0}d_{1}-14d_{0}-6d_{1}}{2(5d_{0}^{2}+d_{1}^{2}+4d_{0}d_{1})}
$$

In [ ]:
#求alpha 
def determineStepSize(x,d):
    #alpha=
    return alpha

In [ ]:
determineStepSize(xk[0],dk[0])

<hr>
Step 3: Set ${\bf x}^{k+1} \leftarrow {\bf x}^{k} + \alpha^{k} {\bf d}^{k}$, $k \leftarrow k+1$.Go to Step 1.

In [ ]:
Q=np.array([[10,4],[4,2]])
q=np.array([[-14],[-6]])
#給定xk
#xk=[np.array([[0],[10]])]      
#隨機起始值
xk=[np.array([[random.randint(-10, 10)],[random.randint(-10, 10)]])]
k=0
dk=[]
alphak=[]
dk.append(-functionGradient(xk[0]))

while np.linalg.norm(dk[k])>1e-6 and k<=100:    #dk值小於1e-6 或 超過100次迭代停止
    #